# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 629)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color:#a4dafb;")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("""
            background-color:white;
            color:#eb6666;
            font-weight:900;
            font-size:14px;
            border-radius:10px;
            border: 1px solid #554c4d;
        """)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setStyleSheet("""
            background-color:white;
            border-radius:20px;
            border: 2px solid #554c4d;
        """)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4.addWidget(self.widget_3)
        
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setStyleSheet("""
            background-color:white;
            border-radius:20px;
            border: 2px solid #554c4d;
        """)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4.addWidget(self.widget_4)
        
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setStyleSheet("""
            background-color:white;
            border-radius:20px;
            border: 2px solid #554c4d;
        """)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_4.addWidget(self.widget_5)
        
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setStyleSheet("""
            background-color:white;
            border-radius:20px;
            border: 2px solid #554c4d;
        """)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4.addWidget(self.widget_6)
        
        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        self.widget_7.setStyleSheet("""
            background-color:white;
            border-radius:20px;
            border: 2px solid #554c4d;
        """)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_4.addWidget(self.widget_7)
        
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("""
            background-color:#fbcbd3;
            color:#554c4d;
            font-weight:900;
            font-size:18px;
            border-radius:10px;
        """)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("""
            background-color:white;
            border-radius:20px;
            border: 2px solid #554c4d;
        """)
        self.widget.setObjectName("widget")
        
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setStyleSheet("""
            color:#554c4d;
            font-weight:900;
            font-size:18px;
            border-radius:10px;
            border: 1px solid #554c4d;
        """)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setStyleSheet("""
            color: #eb6666;
            font-weight:900;
            font-size:18px;
            border-radius:10px;
            border:none;
        """)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 1, 1, 1)
        
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setStyleSheet("""
            color:#554c4d;
            font-weight:900;
            font-size:18px;
            border-radius:10px;
            border: 1px solid #554c4d;
        """)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setStyleSheet("""
            color:#554c4d;
            font-weight:900;
            font-size:18px;
            border-radius:10px;
            border: 1px solid #554c4d;
        """)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setStyleSheet("""
            color: #eb6666;
            font-weight:900;
            font-size:18px;
            border-radius:10px;
            border:none;
        """)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 1, 1, 1)
        
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setStyleSheet("""
            color: #eb6666;
            font-weight:900;
            font-size:18px;
            border-radius:10px;
            border:none;
        """)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 1, 1, 1)
        
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setStyleSheet("""
            color:#554c4d;
            font-weight:900;
            font-size:18px;
            border-radius:10px;
            border: 1px solid #554c4d;
        """)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setStyleSheet("""
            color: #eb6666;
            border:none;
            font-weight:900;
            font-size:18px;
            border-radius:10px;
        """)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 3, 1, 1, 1)
        
        self.verticalLayout_2.addWidget(self.widget)
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("""
            background-color:#fbcbd3;
            color:#554c4d;
            font-weight:900;
            font-size:18px;
            border-radius:10px;
        """)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("""
            background-color:white;
            border-radius:20px;
            border: 2px solid #554c4d;
        """)
        self.widget_2.setObjectName("widget_2")
        
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem1, 0, 0, 1, 1)
        
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setStyleSheet("""
            color: #eb6666;
            border:none;
            font-weight:900;
            font-size:18px;
            border-radius:10px;
        """)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        
        self.verticalLayout_2.addWidget(self.widget_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Upload Data"))
        self.label.setText(_translate("MainWindow", "Vitals"))
        self.label_9.setText(_translate("MainWindow", "SpO2"))
        self.label_11.setText(_translate("MainWindow", "__"))
        self.label_8.setText(_translate("MainWindow", "Blood Pressure"))
        self.label_7.setText(_translate("MainWindow", "Heart rate"))
        self.label_13.setText(_translate("MainWindow", "__"))
        self.label_12.setText(_translate("MainWindow", "__"))
        self.label_10.setText(_translate("MainWindow", "Temperature"))
        self.label_14.setText(_translate("MainWindow", "__"))
        self.label_2.setText(_translate("MainWindow", "Heart Rhythm"))
        self.label_4.setText(_translate("MainWindow", "Normal"))